{{- if .Values.action.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aerie.fullname" . }}-action
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.componentLabels" (dict "root" . "component" "action") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.action.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "aerie.componentSelectorLabels" (dict "root" . "component" "action") | nindent 4 }}
{{- end }}
