{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aerie.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.componentLabels" (dict "root" . "component" "gateway") | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "aerie.componentSelectorLabels" (dict "root" . "component" "gateway") | nindent 4 }}
{{- end }}
